//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V5Entities4 : DbContext
    {
        public V5Entities4()
            : base("name=V5Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HC_CLIENT> HC_CLIENT { get; set; }
        public virtual DbSet<HC_CLIENT_BRANCH> HC_CLIENT_BRANCH { get; set; }
        public virtual DbSet<HC_REQUISITION_MAPPING> HC_REQUISITION_MAPPING { get; set; }
        public virtual DbSet<HC_REQUISITION_STATUS> HC_REQUISITION_STATUS { get; set; }
        public virtual DbSet<HC_REQUISITIONS> HC_REQUISITIONS { get; set; }
        public virtual DbSet<HC_RESUME_BANK> HC_RESUME_BANK { get; set; }
        public virtual DbSet<HC_USER_MAIN> HC_USER_MAIN { get; set; }
        public virtual DbSet<HCM_CURRENCY> HCM_CURRENCY { get; set; }
        public virtual DbSet<HCM_LOCATIONS> HCM_LOCATIONS { get; set; }
        public virtual DbSet<HCM_NATIONALITY> HCM_NATIONALITY { get; set; }
        public virtual DbSet<HCM_BRANCH> HCM_BRANCH { get; set; }
    }
}
