//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_APPROVAL_LOG
    {
        public long Rid { get; set; }
        public long CBRid { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public string Reject_comment { get; set; }
    }
}
