//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CL_CLOSING_BLOCK
    {
        public long client { get; set; }
        public string Clients { get; set; }
        public string jd { get; set; }
        public string jobcode1 { get; set; }
        public string Jobcode { get; set; }
        public string lob { get; set; }
        public long location { get; set; }
        public string pr { get; set; }
        public string br { get; set; }
        public string req { get; set; }
        public long Requirement { get; set; }
        public string status1 { get; set; }
        public long RID { get; set; }
        public long ClientID { get; set; }
        public long Reqid { get; set; }
        public Nullable<long> Status { get; set; }
        public string Fname { get; set; }
        public string EmailId { get; set; }
        public string PNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedUser { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DOB { get; set; }
        public string ANumber { get; set; }
        public string CLocation { get; set; }
        public string LocPref { get; set; }
        public string WorkLoc { get; set; }
        public string DistHoToWorkLoc { get; set; }
        [DisplayFormat(DataFormatString = "{0:G29}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> TExp { get; set; }
        [DisplayFormat(DataFormatString = "{0:G29}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> RExp { get; set; }
        public string Ccompany { get; set; }
        public string EmpType { get; set; }
        public string ReasonJobChange { get; set; }
        public string WorkVisaStatus { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> VisaValidDate { get; set; }
        public string NationalityID { get; set; }
        [DisplayFormat(DataFormatString = "{0:G29}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> GPPerHour { get; set; }
        public string GPM { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string NoticePeriod { get; set; }
        public string AvailJoinDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ConProjEndDate { get; set; }
        public string SameClient { get; set; }
        public string ResonForLeaving { get; set; }
        public string Interviews { get; set; }
        public string OfferRecieved { get; set; }
        public string Offer { get; set; }
        public string AvailabilityStatus { get; set; }
        public string PlannedHolidays { get; set; }
        [DisplayFormat(DataFormatString = "{0:G29}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> CurrentSalary { get; set; }
        [DisplayFormat(DataFormatString = "{0:G29}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> ExpectedSalary { get; set; }
        [DisplayFormat(DataFormatString = "{0:G29}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> Payrate { get; set; }
        public string ClosedPaye { get; set; }
        public string LoadedPayRate { get; set; }
        [DisplayFormat(DataFormatString = "{0:G29}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> PurposedBillRate { get; set; }
        public string Insurance { get; set; }
        public string BGVStatus { get; set; }
        public string Imagepath { get; set; }
        public string interviewDetails { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<long> modifieduser { get; set; }
        public string Holidays { get; set; }
        public string TeleInterview { get; set; }
        public string FaceInterview { get; set; }
        public string FInterview { get; set; }
    }
}
