//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_mapping
    {
        public long RID { get; set; }
        public long RecID { get; set; }
        public long ManagerID { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual CL_USERS CL_USERS { get; set; }
    }
}
