//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_CLIENT
    {
        public long RID { get; set; }
        public string Title { get; set; }
        public string RefID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public long TID { get; set; }
        public short IsLead { get; set; }
        public string Address { get; set; }
        public long AccountManager { get; set; }
        public string Notes { get; set; }
        public Nullable<short> StageID { get; set; }
        public Nullable<short> StageStatusID { get; set; }
        public string LeadNo { get; set; }
        public string GroupName { get; set; }
        public long IndustryTypeID { get; set; }
        public string PhoneNo { get; set; }
        public string Website { get; set; }
        public long CountryID { get; set; }
        public long StateID { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public long ProbabilityID { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public string OpportunityTitle { get; set; }
        public long LeadType { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Territory { get; set; }
        public Nullable<decimal> RevenueAmount { get; set; }
        public Nullable<decimal> RevenueCurrency { get; set; }
        public Nullable<short> RevenueDuration { get; set; }
        public Nullable<long> RefLeadID { get; set; }
        public bool IsDataSync { get; set; }
        public Nullable<System.DateTime> LastDataSyncDate { get; set; }
        public Nullable<long> Anchor { get; set; }
        public long ProfitCenterId { get; set; }
        public Nullable<short> ExtClientStatus { get; set; }
        public long AccountManager2 { get; set; }
        public long AccountManager3 { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public bool ExtIsExtendable { get; set; }
        public decimal ExtRevenue { get; set; }
        public bool IsMSP { get; set; }
        public Nullable<long> ClientGeoID { get; set; }
        public Nullable<decimal> Utilization { get; set; }
        public string ExtClientCode { get; set; }
        public string ExtClientNameinInvoice { get; set; }
        public string ExtClientOfferLetter { get; set; }
        public long V4RID { get; set; }
        public Nullable<bool> IsLeavesBillable { get; set; }
        public Nullable<bool> IsHolidaysBillable { get; set; }
        public Nullable<short> BillingCalculationMethod { get; set; }
        public Nullable<long> CalculationTypeID { get; set; }
        public Nullable<decimal> BGCheckCost { get; set; }
        public Nullable<short> Rebate { get; set; }
        public Nullable<decimal> SodexoCoupons { get; set; }
        public Nullable<decimal> Holidays { get; set; }
        public Nullable<decimal> TargetGPM { get; set; }
        public Nullable<short> VMOFee { get; set; }
        public Nullable<short> HoursPerDay { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> BillingPoc { get; set; }
        public string ExtVMORate { get; set; }
        public string ExtVMOExtRate { get; set; }
        public Nullable<long> ExtDeliveryManagerID { get; set; }
        public Nullable<short> VMOExtFee { get; set; }
        public Nullable<bool> IsMarkUp { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string ExClientCountry { get; set; }
        public string ExtTower { get; set; }
        public string ExtCCategory { get; set; }
        public string ExtCCCategory { get; set; }
        public string ExtTargetClosureMonth { get; set; }
        public string Prefix { get; set; }
        public Nullable<long> LastNumber { get; set; }
        public string Suffix { get; set; }
        public string ExtAccountManager { get; set; }
        public Nullable<short> ExtVMOTypeID { get; set; }
        public Nullable<short> ExtVMOSubTypeID { get; set; }
        public Nullable<short> ExtVMOExtTypeID { get; set; }
        public Nullable<short> ExtVMOExtSubTypeID { get; set; }
        public Nullable<short> ExtShiftAllowanceID { get; set; }
        public short BillrateCalcBasedonMarkup { get; set; }
        public short ITInputTypeGPGPM { get; set; }
        public decimal ITCompValueGPGPM { get; set; }
        public short NonITRequirementGPGPM { get; set; }
        public short NonITInputTypeGPGPM { get; set; }
        public decimal NonITCompValueGPGPM { get; set; }
        public Nullable<long> LeaveTemplateID { get; set; }
        public Nullable<short> ExtSeverancePay { get; set; }
        public Nullable<decimal> ExtEmployeePastCost { get; set; }
        public decimal NonITOtherCostPerc { get; set; }
        public decimal NonITTargetGPM { get; set; }
        public Nullable<decimal> OtherCostPerc { get; set; }
        public short IsGratuityApplicableForGPGPM { get; set; }
    }
}
