//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_REQUISITION_MAPPING
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public long MappingID { get; set; }
        public short Type { get; set; }
    }
}
