//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_LOCATIONS
    {
        public long RID { get; set; }
        public string Title { get; set; }
        public string PinCode { get; set; }
        public string IncludeAlias { get; set; }
        public string ExcludeAlias { get; set; }
        public long StateID { get; set; }
        public long GroupID { get; set; }
        public long ZoneID { get; set; }
        public long CategoryID { get; set; }
        public bool IsMetro { get; set; }
        public short LocationType { get; set; }
        public string RefID { get; set; }
        public string STDCode { get; set; }
        public bool Status { get; set; }
        public Nullable<long> BaseLocationID { get; set; }
        public short LanguageType { get; set; }
        public long EngKeyID { get; set; }
        public long CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public bool IsCompany { get; set; }
        public long TID { get; set; }
        public bool IsDataSync { get; set; }
        public Nullable<System.DateTime> LastDataSyncDate { get; set; }
        public Nullable<long> LocationCategoryID { get; set; }
        public long V4RID { get; set; }
    }
}
