//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_BRANCH
    {
        public long RID { get; set; }
        public string Name { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public long V4RID { get; set; }
        public short ConsiderGPGPMConfigComputation { get; set; }
        public short ITRequirementGPGPM { get; set; }
        public short ITInputTypeGPGPM { get; set; }
        public decimal ITCompValueGPGPM { get; set; }
        public short NonITRequirementGPGPM { get; set; }
        public short NonITInputTypeGPGPM { get; set; }
        public decimal NonITCompValueGPGPM { get; set; }
        public decimal ITTargetGPM { get; set; }
        public decimal NonITTargetGPM { get; set; }
        public decimal NonITOtherCostPerc { get; set; }
        public decimal ITOtherCostPerc { get; set; }
    }
}
