//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_CURRENCY
    {
        public long RID { get; set; }
        public long TID { get; set; }
        public string Currency { get; set; }
        public string RefID { get; set; }
        public decimal Factor { get; set; }
        public string HelpText { get; set; }
        public string CurrencyCode { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public short LanguageType { get; set; }
        public long EngKeyID { get; set; }
        public long CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string CurrencyCulture { get; set; }
        public Nullable<long> V4RID { get; set; }
    }
}
