//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IHD_DBEntities12 : DbContext
    {
        public IHD_DBEntities12()
            : base("name=IHD_DBEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CL_CLOSING_BLOCK> CL_CLOSING_BLOCK { get; set; }
        public virtual DbSet<cl_mapping> cl_mapping { get; set; }
        public virtual DbSet<CL_USERS> CL_USERS { get; set; }
        public virtual DbSet<IHD_USER_MAIN> IHD_USER_MAIN { get; set; }
        public virtual DbSet<USER_LIST_TEST> USER_LIST_TEST { get; set; }
        public virtual DbSet<CL_APPROVAL_LOG> CL_APPROVAL_LOG { get; set; }
    
        public virtual ObjectResult<IHD_cl_details_Result> IHD_cl_details(Nullable<long> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IHD_cl_details_Result>("IHD_cl_details", ridParameter);
        }
    
        public virtual int sp_Approve(Nullable<long> userid, Nullable<long> rid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Approve", useridParameter, ridParameter);
        }
    
        public virtual ObjectResult<sp_APPROVE_block_Result> sp_APPROVE_block(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_APPROVE_block_Result>("sp_APPROVE_block", useridParameter);
        }
    
        public virtual ObjectResult<sp_cb_closing_block_count_Result> sp_cb_closing_block_count(Nullable<long> userid, Nullable<long> rightsid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var rightsidParameter = rightsid.HasValue ?
                new ObjectParameter("rightsid", rightsid) :
                new ObjectParameter("rightsid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cb_closing_block_count_Result>("sp_cb_closing_block_count", useridParameter, rightsidParameter);
        }
    
        public virtual ObjectResult<sp_cb_closing_block_dash_Result> sp_cb_closing_block_dash(Nullable<long> userid, Nullable<long> rightsid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var rightsidParameter = rightsid.HasValue ?
                new ObjectParameter("rightsid", rightsid) :
                new ObjectParameter("rightsid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cb_closing_block_dash_Result>("sp_cb_closing_block_dash", useridParameter, rightsidParameter);
        }
    
        public virtual ObjectResult<sp_cb_closing_block_dashmanager_Result> sp_cb_closing_block_dashmanager(Nullable<long> userid, Nullable<long> rightsid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var rightsidParameter = rightsid.HasValue ?
                new ObjectParameter("rightsid", rightsid) :
                new ObjectParameter("rightsid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cb_closing_block_dashmanager_Result>("sp_cb_closing_block_dashmanager", useridParameter, rightsidParameter);
        }
    
        public virtual ObjectResult<sp_cb_pending_block_Result> sp_cb_pending_block(Nullable<long> userid, Nullable<long> rightsid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var rightsidParameter = rightsid.HasValue ?
                new ObjectParameter("rightsid", rightsid) :
                new ObjectParameter("rightsid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cb_pending_block_Result>("sp_cb_pending_block", useridParameter, rightsidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_cb_reject_block_count(Nullable<long> userid, Nullable<long> rightsid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var rightsidParameter = rightsid.HasValue ?
                new ObjectParameter("rightsid", rightsid) :
                new ObjectParameter("rightsid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_cb_reject_block_count", useridParameter, rightsidParameter);
        }
    
        public virtual ObjectResult<sp_cl_details_Result> sp_cl_details(Nullable<long> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cl_details_Result>("sp_cl_details", ridParameter);
        }
    
        public virtual ObjectResult<sp_cl_details_1_Result> sp_cl_details_1(Nullable<long> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cl_details_1_Result>("sp_cl_details_1", ridParameter);
        }
    
        public virtual ObjectResult<sp_cl_details_2_Result> sp_cl_details_2(Nullable<long> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cl_details_2_Result>("sp_cl_details_2", ridParameter);
        }
    
        public virtual ObjectResult<sp_cl_search_details_Result> sp_cl_search_details(string nameemail)
        {
            var nameemailParameter = nameemail != null ?
                new ObjectParameter("nameemail", nameemail) :
                new ObjectParameter("nameemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cl_search_details_Result>("sp_cl_search_details", nameemailParameter);
        }
    
        public virtual int sp_delete_block(Nullable<long> userid, Nullable<long> rid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_block", useridParameter, ridParameter);
        }
    
        public virtual ObjectResult<sp_reject_block_Result> sp_reject_block(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reject_block_Result>("sp_reject_block", useridParameter);
        }
    
        public virtual int sp_Reject_Test(Nullable<long> userid, Nullable<long> rid, string comment)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(long));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Reject_Test", useridParameter, ridParameter, commentParameter);
        }
    }
}
