//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHD_USER_MAIN
    {
        public long RID { get; set; }
        public long userid { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public short Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long DivisionID { get; set; }
        public long LocationID { get; set; }
        public long RightsID { get; set; }
        public long Status { get; set; }
        public string EmailID { get; set; }
        public string Mobile { get; set; }
        public Nullable<long> TeamID { get; set; }
        public Nullable<long> AccessRights { get; set; }
        public Nullable<long> ReportsTo { get; set; }
        public string AccessLevel { get; set; }
        public Nullable<short> AccessType { get; set; }
        public Nullable<short> ISRecruiter { get; set; }
        public Nullable<short> ISTeamLeader { get; set; }
        public Nullable<short> ISOpManager { get; set; }
        public Nullable<short> ISBuManager { get; set; }
        public Nullable<short> ISHRManager { get; set; }
        public Nullable<short> ISTopManager { get; set; }
        public short ISPartner { get; set; }
        public short InProcessNotification { get; set; }
        public short ResumeNotification { get; set; }
        public short BlockedResumeNotification { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public long CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ADSUserID { get; set; }
        public long ModifiedUserID { get; set; }
        public string EmployeeID { get; set; }
        public long InvoiceLocID { get; set; }
        public Nullable<long> V5RID { get; set; }
        public string pswd { get; set; }
    }
}
