//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LIST_TEST
    {
        public long RID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public short Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long LocationID { get; set; }
        public long Status { get; set; }
        public string EmailID { get; set; }
        public string Mobile { get; set; }
        public long CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public long ModifiedUserID { get; set; }
        public long Gender { get; set; }
        public System.DateTime DOB { get; set; }
    }
}
