//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetEmployeeData
    {
        public long RID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeID { get; set; }
        public long RMID { get; set; }
        public string RMName { get; set; }
        public short StatusID { get; set; }
        public string Status { get; set; }
        public System.DateTime JoiningDate { get; set; }
    }
}
