//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetCOstatistics
    {
        public int COToday { get; set; }
        public int CandidateReference { get; set; }
        public int CandidateReferal { get; set; }
    }
}
