//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetReqNDReportData
    {
        public long RID { get; set; }
        public long ReqResID { get; set; }
        public long ResID { get; set; }
        public string CandidateName { get; set; }
        public string MobileNo { get; set; }
        public string RequisitionTitle { get; set; }
        public string JobCode { get; set; }
        public int Positions { get; set; }
        public string RequisitionStatus { get; set; }
        public string TicketNo { get; set; }
        public long AssignedTo { get; set; }
        public string StageTitle { get; set; }
        public string StatusTitle { get; set; }
        public string EmailID { get; set; }
        public string ReqCreatedDate { get; set; }
        public string ReqCreatedUser { get; set; }
        public string ReqLocation { get; set; }
        public string Department { get; set; }
        public string CreatedUser { get; set; }
        public long CreatedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public long ModifiedUserID { get; set; }
        public long ReqID { get; set; }
        public Nullable<bool> IsOfferMade { get; set; }
        public int StageLevel { get; set; }
        public int StatusLevel { get; set; }
        public string Code { get; set; }
        public long GradeID { get; set; }
        public string Grade { get; set; }
        public long JoiningLocationID { get; set; }
        public long ClientID { get; set; }
        public string clientName { get; set; }
        public string Location { get; set; }
        public long DesignationID { get; set; }
        public string Designation { get; set; }
        public long SourceID { get; set; }
        public string SourceName { get; set; }
        public long SourceGroupID { get; set; }
        public string SourceGroup { get; set; }
        public string SourceEmailId { get; set; }
        public long SourceUserID { get; set; }
        public string SourceUser { get; set; }
        public long WFID { get; set; }
        public Nullable<int> Ageing { get; set; }
        public Nullable<long> StageID { get; set; }
        public Nullable<long> StatusID { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.DateTime PlannedJoiningDate { get; set; }
        public string Recommendation { get; set; }
        public string SBU { get; set; }
        public string EStatus { get; set; }
        public string Requester { get; set; }
    }
}
