//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Getuserdata
    {
        public long RID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNo { get; set; }
        public long SalutationId { get; set; }
        public string Salutation { get; set; }
        public string Photo { get; set; }
        public long GenderID { get; set; }
        public string Gender { get; set; }
        public long GradeID { get; set; }
        public string Grade { get; set; }
        public string DOB { get; set; }
        public long ConfigTemplateID { get; set; }
        public string ConfigTemplate { get; set; }
        public string EmailID { get; set; }
        public string EmailSignature { get; set; }
        public string MobileNo { get; set; }
        public string UserName { get; set; }
        public string Designation { get; set; }
        public long DesignationID { get; set; }
        public string ReportingUser { get; set; }
        public long ReportingToID { get; set; }
        public string TIDTitle { get; set; }
        public long TID { get; set; }
        public string StatusMessage { get; set; }
        public bool Status { get; set; }
        public string Notes { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Roles { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsDataSync { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public short CalendarDefaultViewId { get; set; }
        public string CalendarDefaultView { get; set; }
        public bool IsPrimary { get; set; }
        public long BloodGroupId { get; set; }
        public string BloodGroup { get; set; }
        public string Flag { get; set; }
        public string AccessibleEntities { get; set; }
        public string AccessibleClients { get; set; }
        public long TimeZoneid { get; set; }
        public string TimeZone { get; set; }
        public string EmployerID { get; set; }
        public long VenueID { get; set; }
        public string Venue { get; set; }
        public long CurrencyID { get; set; }
        public string DateFormat { get; set; }
        public string Currency { get; set; }
        public long DurationID { get; set; }
        public string Duration { get; set; }
    }
}
