//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetResumeData
    {
        public long RID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string DOB { get; set; }
        public long SalutationId { get; set; }
        public string Salutation { get; set; }
        public decimal TotalExp { get; set; }
        public decimal RelevantExp { get; set; }
        public string ResSummary { get; set; }
        public string HotNotes { get; set; }
        public bool IsFresher { get; set; }
        public string ExpLevel { get; set; }
        public string ExperienceRange { get; set; }
        public short ResType { get; set; }
        public string ResumeType { get; set; }
        public short NoticePeriod { get; set; }
        public string CandidateNo { get; set; }
        public long SourceID { get; set; }
        public string Source { get; set; }
        public long SourceGroupID { get; set; }
        public string SourceGroup { get; set; }
        public long SourceUserID { get; set; }
        public string SourceUser { get; set; }
        public string SourceEmailId { get; set; }
        public string Notes { get; set; }
        public short ResStatusID { get; set; }
        public string ResStatus { get; set; }
        public long PresentCurrencyID { get; set; }
        public string PresentCurrency { get; set; }
        public long PresentScaleID { get; set; }
        public string PresentScale { get; set; }
        public decimal PresentCTC { get; set; }
        public long ExpectedCurrencyID { get; set; }
        public string ExpectedCurrency { get; set; }
        public long ExpectedScaleID { get; set; }
        public string ExpectedScale { get; set; }
        public decimal ExpectedCTC { get; set; }
        public decimal ExpectedHike { get; set; }
        public bool Status { get; set; }
        public string Functions { get; set; }
        public string SubFunctions { get; set; }
        public string Skills { get; set; }
        public long TID { get; set; }
        public string ColourCode { get; set; }
        public string CurrentCompany { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string Employer { get; set; }
        public Nullable<bool> DocAvailable { get; set; }
    }
}
