//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_HC_REQ_RESUME_ProjectInfo
    {
        public Nullable<long> ReqResID { get; set; }
        public string TicketNo { get; set; }
        public long ClientContactPersonID { get; set; }
        public long EndClientID { get; set; }
        public bool IsOTApplicable { get; set; }
        public bool IsApplicableCompOff { get; set; }
        public long OTBillCurrency { get; set; }
        public decimal OTBillAmount { get; set; }
        public long OTBillDuration { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<short> POBillingID { get; set; }
        public string BilligGroup { get; set; }
        public string MarkUp { get; set; }
        public string VMORate { get; set; }
        public Nullable<short> VMOTypeID { get; set; }
        public Nullable<short> VMOSubTypeID { get; set; }
        public Nullable<short> VMOExtTypeID { get; set; }
        public Nullable<short> VMOExtSubTypeID { get; set; }
        public string PrintInvoice { get; set; }
        public string MailInvoice { get; set; }
        public Nullable<short> ShiftAllowanceID { get; set; }
        public Nullable<short> NonBillableID { get; set; }
        public Nullable<System.DateTime> NonBillableStartDate { get; set; }
        public Nullable<short> NonBillableTypeID { get; set; }
        public Nullable<System.DateTime> NonBillableEndDate { get; set; }
        public Nullable<long> ReasonID { get; set; }
        public string CCostCenter { get; set; }
        public string VMOExtRate { get; set; }
        public Nullable<short> BillCardID { get; set; }
        public Nullable<bool> IsClientPercentage { get; set; }
        public string VendorPayment { get; set; }
        public string ProjectState { get; set; }
        public string NonBillNotes { get; set; }
        public Nullable<bool> IsMonthlyInvoice { get; set; }
        public string ClientEmpID { get; set; }
        public Nullable<short> MarkUpTypeID { get; set; }
        public Nullable<short> ProjectZoneID { get; set; }
        public Nullable<short> IsConsultant { get; set; }
        public long VendorRateCurrency { get; set; }
        public Nullable<decimal> VendorRateAmount { get; set; }
        public long VendorRateDuration { get; set; }
        public long VOTRateCurrency { get; set; }
        public Nullable<decimal> VOTRateAmount { get; set; }
        public long VOTRateDuration { get; set; }
        public Nullable<bool> IsWO { get; set; }
        public Nullable<long> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long PHBonusType { get; set; }
        public decimal PHBonusAmount { get; set; }
        public short PHOtherTaxIncome { get; set; }
        public string PHOtherIncomeClause { get; set; }
        public string PHOtherBonus { get; set; }
        public string CandidateBenefits { get; set; }
        public Nullable<long> ProjectController { get; set; }
    }
}
