//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_HC_RESUME_BANK
    {
        public decimal TotalExp { get; set; }
        public decimal RelevantExp { get; set; }
        public short NoticePeriod { get; set; }
        public long SourceID { get; set; }
        public long PresentCurrency { get; set; }
        public decimal PresentCTC { get; set; }
        public long PresentScale { get; set; }
        public long PresentCTCDuration { get; set; }
        public long ExpectedCurrency { get; set; }
        public decimal ExpectedCTC { get; set; }
        public long ExpectedScale { get; set; }
        public long ExpectedCTCDuration { get; set; }
        public string CandidateNo { get; set; }
        public string SourceEmailId { get; set; }
        public string HotNotes { get; set; }
        public string PanNo { get; set; }
        public string PassportNo { get; set; }
        public string Notes { get; set; }
        public long CUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long MUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public long Designation { get; set; }
        public System.DateTime DOB { get; set; }
        public string PhoneNo { get; set; }
        public int Gender { get; set; }
        public long Salutation { get; set; }
        public long Nationality { get; set; }
        public long Location { get; set; }
        public long StateID { get; set; }
        public long CountryID { get; set; }
        public string Pincode { get; set; }
        public string Address1 { get; set; }
        public long CurrentLocation { get; set; }
        public long CurrentStateID { get; set; }
        public long CurrentCountryID { get; set; }
        public string CurrentPincode { get; set; }
        public string Address2 { get; set; }
        public long RID { get; set; }
        public string PreferLocation { get; set; }
        public string ResStatus { get; set; }
        public long SourceGroupID { get; set; }
        public string ExEmployeeID { get; set; }
        public string RefEmpID { get; set; }
        public string VendorPassthrough { get; set; }
        public string AadharNo { get; set; }
        public long MaritalStatus { get; set; }
        public string ResumeSource { get; set; }
    }
}
