//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_HC_REQ_RESUME_forIssue
    {
        public long RID { get; set; }
        public string CandidateNo { get; set; }
        public string ReqNumber { get; set; }
        public string StageTitle { get; set; }
        public string StatusTitle { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public long ModifiedUser { get; set; }
        public long SourceID { get; set; }
        public long SourceGroup { get; set; }
        public long Grade { get; set; }
        public long Location { get; set; }
        public decimal OfferedCTC { get; set; }
        public Nullable<System.DateTime> PlannedJoiningDate { get; set; }
        public string TicketNo { get; set; }
        public long OfferDesignation { get; set; }
        public Nullable<System.DateTime> JoinedOn { get; set; }
        public long Designation { get; set; }
        public long OfferLocation { get; set; }
        public long ResID { get; set; }
        public long ReqID { get; set; }
        public int ProcessTemplateID { get; set; }
        public decimal JoiningBonus { get; set; }
        public int JB { get; set; }
        public decimal Buyout { get; set; }
        public int BuyoutAmount { get; set; }
        public decimal RelocationPay { get; set; }
        public decimal VendorFee { get; set; }
        public decimal FreeBillDays { get; set; }
        public string GPM { get; set; }
        public decimal GP { get; set; }
        public long OfferCurrency { get; set; }
        public string OfferFrequency { get; set; }
        public long BillableCurrency { get; set; }
        public string BillableFrequency { get; set; }
        public decimal BillableAmount { get; set; }
        public string GPGPMValues { get; set; }
        public long ContractID { get; set; }
        public long ContractType { get; set; }
        public long VendorContractID { get; set; }
        public long VendorContractTypeID { get; set; }
        public string ResourceManager { get; set; }
        public string Recruiter { get; set; }
        public string PassthroughPayRolling { get; set; }
        public decimal BasicSalaryPHPAmount { get; set; }
        public long BasicCurrency { get; set; }
        public short IsFullPartTime { get; set; }
        public short PTHours { get; set; }
        public short PTDays { get; set; }
        public string ReqCategory { get; set; }
        public long reqClientID { get; set; }
        public long reqbranchID { get; set; }
        public string Redeployment { get; set; }
        public string JobDesc { get; set; }
    }
}
