//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_HC_REQUISITIONS_forIssue
    {
        public string ReqTitle { get; set; }
        public string ReqNumber { get; set; }
        public int NoOfOpenings { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long Designation { get; set; }
        public long Grade { get; set; }
        public string Notes { get; set; }
        public short ReqStatus { get; set; }
        public string Anchor { get; set; }
        public string Requester { get; set; }
        public long Client { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ClosedDate { get; set; }
        public System.DateTime RecievedDate { get; set; }
        public System.DateTime CancelDate { get; set; }
        public string ReportingManager { get; set; }
        public long RID { get; set; }
        public decimal MinExperience { get; set; }
        public decimal MaxExperience { get; set; }
        public long Branch { get; set; }
        public long PositionProfile { get; set; }
        public string ContactEmailID { get; set; }
        public int ProcessTemplateID { get; set; }
        public long SalesSpoc { get; set; }
        public string EmployementType { get; set; }
        public string Skills { get; set; }
        public decimal CTCFromAmount { get; set; }
        public decimal CTCToAmount { get; set; }
        public long CTCCurrency { get; set; }
        public long BillCurrency { get; set; }
        public decimal BillAmount { get; set; }
        public long billDuration { get; set; }
        public int SourcingStatus { get; set; }
        public System.DateTime TargetClosureDate { get; set; }
        public string ReqCateGory { get; set; }
        public string RequirementType { get; set; }
        public string OpportunitySource { get; set; }
        public string ClientCateGory { get; set; }
        public string HotNotes { get; set; }
        public string SourcingGuideline { get; set; }
        public string ExtFireStation { get; set; }
        public string ExtPriority { get; set; }
        public byte[] JobDesc { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public long ExtDD { get; set; }
        public long ExtRL { get; set; }
        public decimal ContractDuration { get; set; }
        public string ReqRegion { get; set; }
        public string SECTOR { get; set; }
    }
}
