//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Lead_GetOpportunityData
    {
        public long RID { get; set; }
        public long ClientID { get; set; }
        public string ClientName { get; set; }
        public short StageID { get; set; }
        public string StageName { get; set; }
        public short StatusID { get; set; }
        public string StatusName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public long CreatedUserID { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public long ModifiedUserID { get; set; }
        public decimal RevenueAmount { get; set; }
        public string RevenueDuration { get; set; }
        public string RevenueCurrency { get; set; }
        public string OpportunityTitle { get; set; }
        public string OpportunityOwner { get; set; }
        public string ClientContactName { get; set; }
        public long ClientContactID { get; set; }
        public System.DateTime ExpectedClosureDate { get; set; }
        public long NoOfResourceRequired { get; set; }
        public string ProjectName { get; set; }
        public string MaxGrade { get; set; }
        public string FinanceID { get; set; }
        public string OrgLevel1Type0 { get; set; }
        public string OrgLevel2Type0 { get; set; }
        public string OrgLevel3Type0 { get; set; }
        public string SalesPerson { get; set; }
        public decimal GrossMargin { get; set; }
        public Nullable<long> NoOfResCountAvailable { get; set; }
    }
}
