//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NDReport_MMOpenPositionReport
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public string SRF_Job_Code { get; set; }
        public string Entity { get; set; }
        public string Process_ID { get; set; }
        public string Cost_Centre { get; set; }
        public string LOB____GOSC_ { get; set; }
        public string Sub_LOB { get; set; }
        public string Process { get; set; }
        public string MM_FL { get; set; }
        public string Complexity { get; set; }
        public string Category { get; set; }
        public string Hiring_Leader { get; set; }
        public string Reporting_Manager { get; set; }
        public string Function__Enabling___Ops_ { get; set; }
        public string Level__Associate___Sr___Associate___Splst___BPS___QA_ { get; set; }
        public string Business_Type__Secialized_Generic_ { get; set; }
        public string Hiring_Type__Migration___Ramp_up___Backfill_ { get; set; }
        public string Name_of_Candidate_Attrited { get; set; }
        public string Designation_of_candidate_attrited { get; set; }
        public string SRF_Month { get; set; }
        public string SRF_Start_Date_ { get; set; }
        public string SRF_End_Date { get; set; }
        public Nullable<int> SRF_Age__Weeks_ { get; set; }
        public Nullable<int> Approved_TAT { get; set; }
        public string Exceeded_TAT___Within_TAT { get; set; }
        public string SRF_Status { get; set; }
        public decimal Billable_FTE { get; set; }
        public int HC_Requirement { get; set; }
        public int Joiners { get; set; }
        public int Offers_in_Hand { get; set; }
        public int Offer_Drop { get; set; }
        public Nullable<int> Pending { get; set; }
        public int Total_Offered { get; set; }
        public int Hired_Within_Approved_TAT { get; set; }
        public int Hired_Outside_Approved_TAT { get; set; }
        public string SRF_Owner { get; set; }
        public string Expected_DOJ { get; set; }
        public string Name_of_Incumbent_Hired { get; set; }
        public string Names_of_Ops_Assesors { get; set; }
        public string Name_of_HR_Assesor { get; set; }
        public string Source { get; set; }
        public string Source_Name { get; set; }
        public string Exception_Approval_Taken { get; set; }
        public string Empl_ID { get; set; }
        public string Male___Female { get; set; }
        public string Offer_Roll_out_Date { get; set; }
        public decimal Payment { get; set; }
        public string Travel { get; set; }
        public decimal Guest_House { get; set; }
        public decimal Relocation { get; set; }
        public decimal JB { get; set; }
        public decimal NP { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string C_TAT_Exception_Taken___Yes_No__ { get; set; }
        public int Resume_Count { get; set; }
        public int Portal { get; set; }
        public int Vendor { get; set; }
        public int Metmate_Plus { get; set; }
        public Nullable<System.DateTime> fltdt { get; set; }
        public Nullable<long> fltuser { get; set; }
    }
}
