//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NDReportOfferDeviation
    {
        public long rid { get; set; }
        public string SAPID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string DateofJoining { get; set; }
        public string OfferCTC { get; set; }
        public string PresentCTC { get; set; }
        public decimal Hike { get; set; }
        public decimal TotalExperience { get; set; }
        public string Qualification { get; set; }
        public string LastEmployer { get; set; }
        public string OfferNotes { get; set; }
        public Nullable<System.DateTime> JDate { get; set; }
    }
}
