//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NDReportCVAddedToRequirement
    {
        public long RID { get; set; }
        public string RecruiterName { get; set; }
        public string BusinessUnit { get; set; }
        public string Department { get; set; }
        public string Role { get; set; }
        public string JobCode { get; set; }
        public string HiringManager { get; set; }
        public string EmploymentType { get; set; }
        public string Location { get; set; }
        public string CandidateName { get; set; }
        public string CandidateEmail { get; set; }
        public string CandidateMobile { get; set; }
        public string CVAddedDate { get; set; }
        public string CVSentDate { get; set; }
        public string CVShortlistedD { get; set; }
        public string LastModifiedDate { get; set; }
        public string CurrentStage { get; set; }
        public string CurrentStatus { get; set; }
        public long ShortlistTAT { get; set; }
        public string SourceGroup { get; set; }
        public string SourceofHire { get; set; }
        public System.DateTime CDate { get; set; }
    }
}
