//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ND_InterviewerPerformanceReport
    {
        public string Interviewer_name { get; set; }
        public int Interview_scheduled { get; set; }
        public int Interview_Selected { get; set; }
        public int Interview_Rejected { get; set; }
        public int Interview_Dropped { get; set; }
        public int Interview_Pending { get; set; }
    }
}
