//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ND_GetLifeCycleReport
    {
        public string Candidate_ID { get; set; }
        public string Ticket_No { get; set; }
        public long ReqID { get; set; }
        public long RID { get; set; }
        public string Candidate_Name { get; set; }
        public string Job_code { get; set; }
        public string Job_Title { get; set; }
        public string Grade { get; set; }
        public string Office_Location { get; set; }
        public string Department { get; set; }
        public string Sub_Process { get; set; }
        public string Business_Unit { get; set; }
        public string Candidate_source_group { get; set; }
        public string Candidate_source_name { get; set; }
        public string Current_stage { get; set; }
        public string Current_Status { get; set; }
        public string Last_status_updated_date { get; set; }
        public string Registration_Date { get; set; }
        public string Screening_Pending_date { get; set; }
        public string Screening_TAT { get; set; }
        public string Pers_Interview_schd_date { get; set; }
        public string Pers_Interview_TAT { get; set; }
        public string Line_Interview_date { get; set; }
        public string Line_interview_TAT { get; set; }
        public string Client_Interview_date { get; set; }
        public string Client_interview_TAT { get; set; }
        public string Offer_made_date { get; set; }
        public string Offer_Made_TAT { get; set; }
        public string Offer_accepted_date { get; set; }
        public string Offer_accept_or_withdraw_TAT { get; set; }
        public string Joining_date__GIS_ { get; set; }
        public string Joining_TAT { get; set; }
        public string Emp_ID { get; set; }
        public string Overall_TAT__screening_to_offer_ { get; set; }
        public string Overall_TAT__screening_to_join_ { get; set; }
        public string Reason_Group { get; set; }
        public string Reject_reason { get; set; }
        public string Batch_ID { get; set; }
        public string Hiring_type { get; set; }
        public decimal CET_score__overall_ { get; set; }
        public string Process_specific_score__overall_ { get; set; }
        public int Personal_interview_rating { get; set; }
        public int Line_interview__rating { get; set; }
        public int Overall_rating { get; set; }
    }
}
