//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NDReport_MMODCReport
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public string Date_of_Joining__DD_MM_YY_ { get; set; }
        public string Re_hire_Status { get; set; }
        public string If_Yes__Previous_Employee_ID { get; set; }
        public string Employee_Full_Name { get; set; }
        public string Salutation__Mr__Ms__ { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Process_Name { get; set; }
        public string Sub_LOB { get; set; }
        public string LOB { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string Reporting_Manager_Name { get; set; }
        public string DOB { get; set; }
        public string Cost_Centre { get; set; }
        public string Prospective_Date_of_Joining { get; set; }
        public string Designation { get; set; }
        public string Grade { get; set; }
        public decimal Basic { get; set; }
        public decimal House_Rent_Allowance__HRA_ { get; set; }
        public decimal Ad_Hoc_Allowance { get; set; }
        public decimal Domiciliary_Medical { get; set; }
        public decimal Leave_Travel_Allowance__LTA_ { get; set; }
        public decimal Conveyance_Car_Plan { get; set; }
        public decimal Vehicle_Maintenance_and_Running_Allowance__VMRA_ { get; set; }
        public decimal Provident_Fund__Employer_s_Contribution_ { get; set; }
        public decimal Gratuity { get; set; }
        public decimal Base_Salary { get; set; }
        public decimal Annual_Variable_Incentive_Plan { get; set; }
        public string CTC { get; set; }
        public Nullable<System.DateTime> fltdt { get; set; }
        public Nullable<long> fltuser { get; set; }
    }
}
