//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NDReportCloseReqTAT
    {
        public long rid { get; set; }
        public string JobCode { get; set; }
        public string BusinessUnit { get; set; }
        public string Department { get; set; }
        public string Role { get; set; }
        public string Designation { get; set; }
        public string RecruiterName { get; set; }
        public string HiringManager { get; set; }
        public string EmploymentType { get; set; }
        public string CandidateName { get; set; }
        public string EmailID { get; set; }
        public string ContactNumber { get; set; }
        public string CurrentEmployer { get; set; }
        public string SourceGroup { get; set; }
        public string SourceofHire { get; set; }
        public string RecruitmentStatus { get; set; }
        public string ReqFinalApprovalDate { get; set; }
        public string CVAddedDate { get; set; }
        public string CVSentHMDate { get; set; }
        public long CVSentTAT { get; set; }
        public string CVShortlistedd { get; set; }
        public long ShortlistedTAT { get; set; }
        public string FirstInterviewScheduled { get; set; }
        public string FinalInterviewShortlisted { get; set; }
        public string OfferMade { get; set; }
        public string OfferAccepted { get; set; }
        public string DateofJoining { get; set; }
        public long TimeTakenToFill { get; set; }
        public long TotalTimeTakenToFill { get; set; }
        public Nullable<System.DateTime> JDate { get; set; }
    }
}
