//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NDReport_VendorJoiningReport
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public string Male___Female { get; set; }
        public string Candidate_Name { get; set; }
        public string LOB { get; set; }
        public string Process_Name { get; set; }
        public string Category { get; set; }
        public string Date_of_Joining { get; set; }
        public decimal Total_Cost { get; set; }
        public string Cost_Centre { get; set; }
        public Nullable<System.DateTime> fltdt { get; set; }
        public Nullable<long> fltuser { get; set; }
    }
}
