//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NDReportGMCAddition
    {
        public long rid { get; set; }
        public string EmpID { get; set; }
        public string SAPID { get; set; }
        public string PrimaryInsuredName { get; set; }
        public string DateofBirth { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string RelationType { get; set; }
        public string Dependent1 { get; set; }
        public string DateofBirth1 { get; set; }
        public int Age1 { get; set; }
        public string Gender1 { get; set; }
        public string RelationType1 { get; set; }
        public string Dependent2 { get; set; }
        public string DateofBirth2 { get; set; }
        public int Age2 { get; set; }
        public string Gender2 { get; set; }
        public string RelationType2 { get; set; }
        public string Dependent3 { get; set; }
        public string DateofBirth3 { get; set; }
        public int Age3 { get; set; }
        public string Gender3 { get; set; }
        public string RelationType3 { get; set; }
        public string DateofJoining { get; set; }
        public string RiskInceptionDate { get; set; }
        public string OfferCTC { get; set; }
        public string SumInsured { get; set; }
        public string EmailID { get; set; }
        public string ContactNumber { get; set; }
        public string GradeDesignation { get; set; }
        public Nullable<System.DateTime> JDate { get; set; }
    }
}
