//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NDReport_OfferTrackerReport
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public string RACF_ID { get; set; }
        public string SRF_No_ { get; set; }
        public string Entity { get; set; }
        public string Process_ID { get; set; }
        public string Cost_Centre { get; set; }
        public string LOB { get; set; }
        public string Sub_LOB { get; set; }
        public string MM_FL { get; set; }
        public string Process_Name { get; set; }
        public string Hiring_Leader { get; set; }
        public string Reporting_Manager { get; set; }
        public string Functional_Leader { get; set; }
        public string C_Function_Enabling___Ops__ { get; set; }
        public string Grade { get; set; }
        public string C_Level___Associate___Sr___Associate__Splst___BPS___QA__TL___AM___UM___Mgr___Sr_Mgr___SDL___Dir__ { get; set; }
        public string C_Work_Type__Generic__Specialized__ { get; set; }
        public string Hiring_Type__Migration___Ramp_up___Backfill___Predictive_Backfill_ { get; set; }
        public string Name_of_Candidate_Attrited { get; set; }
        public string Designation_of_candidate_attrited { get; set; }
        public string SRF_Date { get; set; }
        public string SRF_Month { get; set; }
        public Nullable<int> SRF_Age__Weeks_ { get; set; }
        public Nullable<int> Approved_TAT { get; set; }
        public string Requisition__Open___Closed___On_Hold___Cancel_ { get; set; }
        public string SRF_Owner { get; set; }
        public decimal Billable_FTE { get; set; }
        public decimal Buffer_HC { get; set; }
        public int HC_Requirement { get; set; }
        public int Offered__1_0_ { get; set; }
        public int Joined__1_0_ { get; set; }
        public string Male___Female { get; set; }
        public string Candidate_Name { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string JD_Share_Date { get; set; }
        public string Channel { get; set; }
        public string Source_Details { get; set; }
        public string Resume_Received_Date__Supplier_Process_ { get; set; }
        public string HR_Screening_Completion_Date { get; set; }
        public string Business_Intimated_Date { get; set; }
        public string Business_Interaction_Closure_Date { get; set; }
        public string Candiate_Status { get; set; }
        public string Feedback { get; set; }
        public string HRBP_Closure_Date { get; set; }
        public string Offer_Roll_out_Date { get; set; }
        public string Date_of_Joining { get; set; }
        public Nullable<int> Time_Taken_to_Identify_a_Resource { get; set; }
        public Nullable<int> Time_Taken_to_Onboard { get; set; }
        public string Names_of_Ops_Assesors_Hiring_Manager___Contact_Number { get; set; }
        public string C_Assesment_Single___Dual__ { get; set; }
        public string Client_Assessment { get; set; }
        public string Exception_Approval_Taken_on_Comp { get; set; }
        public string Compensation_approved_by { get; set; }
        public Nullable<int> Exceeded_TAT__0___Within_TAT_1_ { get; set; }
        public string Last_Fixed_Compensation_of_Offered_Candidate { get; set; }
        public string Last_Variable_Compensation_of_Offered_Candidate { get; set; }
        public string Last_TOTAL_CTC_of_Offered_Candidate { get; set; }
        public string Compensation_offered_at_MetLife_Fixed { get; set; }
        public Nullable<long> Compensation_offered_at_MetLife_Total { get; set; }
        public string Travel_Cost { get; set; }
        public decimal Guest_House_Cost { get; set; }
        public decimal Relocation_Cost { get; set; }
        public decimal Joining_Bonus { get; set; }
        public decimal Notice_Period_Payout { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string DOB { get; set; }
        public string Higest_Education_Level { get; set; }
        public string Marital_Status { get; set; }
        public string PAN_ID { get; set; }
        public string Home_Address_1 { get; set; }
        public string Home_Address_2 { get; set; }
        public string Home_Address_3 { get; set; }
        public string Home_City { get; set; }
        public int Postal_Code { get; set; }
        public string ZONE___Delhi___North___South__East__West__Ghaziabad_Gurgaon__Noida__Faridabad { get; set; }
        public string Alt_Phone { get; set; }
        public string Mobile_phone__Country_Area_Number { get; set; }
        public string Permanent_Address { get; set; }
        public string Father_s_Name { get; set; }
        public string Graduation__Stream_ { get; set; }
        public string Post_Graduation { get; set; }
        public string E_mail_ID { get; set; }
        public string College_Name___University_Name { get; set; }
        public int Year_of_Passing { get; set; }
        public decimal Total_Work_Exp__In_Months { get; set; }
        public short Tenure_in_Previous_Organization__In_Months_ { get; set; }
        public string C_Language_1_Read_ { get; set; }
        public string C_Language_2_Read_ { get; set; }
        public string C_Language_3_Read_ { get; set; }
        public string C_Language_4_Read_ { get; set; }
        public string C_Language_5_Read_ { get; set; }
        public string Rehire { get; set; }
        public decimal C_Finance_Test_Score70__ { get; set; }
        public decimal C_Handwriting_Scores_70__ { get; set; }
        public decimal Comprehension_Passage_Scores { get; set; }
        public decimal E_mail_response_writing { get; set; }
        public decimal Score__Grammar { get; set; }
        public decimal Score__Data_Handling_Ability { get; set; }
        public decimal Score__Computer_Proficiency_ { get; set; }
        public decimal Score__Aptitude_Test___Logical___Reasoning__ { get; set; }
        public decimal Numerical_Ability { get; set; }
        public decimal Score__Keyboard_Speed_ { get; set; }
        public decimal Accuracy { get; set; }
        public string Voice_Assessor { get; set; }
        public string HR_Assessor { get; set; }
        public string Passport_Status { get; set; }
        public string Valid_Visa___Country_ { get; set; }
        public decimal Basic { get; set; }
        public decimal C_House_Rent_Allowance__HRA__ { get; set; }
        public decimal C_Conveyance_Allowance_ { get; set; }
        public decimal C_Ad_Hoc_Allowance_ { get; set; }
        public decimal C_Domiciliary_Medical_ { get; set; }
        public decimal C_Leave_Travel_Allowance__LTA__ { get; set; }
        public decimal C_Conveyance_Car_Plan_ { get; set; }
        public decimal C_Vehicle_Maintenance_and_Running_Allowance__VMRA__ { get; set; }
        public decimal C_Provident_Fund__Employer_s_Contribution__ { get; set; }
        public decimal Gratuity { get; set; }
        public string Complexity { get; set; }
        public string Category { get; set; }
        public string Hike__ { get; set; }
        public Nullable<System.DateTime> fltdt { get; set; }
        public Nullable<long> fltuser { get; set; }
    }
}
