//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NDReport_IJPTrackerReport
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public string SRF_Location { get; set; }
        public string IJP_Number { get; set; }
        public string LOB { get; set; }
        public string SLOB { get; set; }
        public string Process_Name { get; set; }
        public string Complexity { get; set; }
        public string Position_Title { get; set; }
        public string Grade { get; set; }
        public string Level_New_Process_Name { get; set; }
        public int Total_No_of_Positions { get; set; }
        public Nullable<int> Number_of_positions_closed { get; set; }
        public Nullable<int> WIP { get; set; }
        public Nullable<int> NTF { get; set; }
        public Nullable<int> Cancelled { get; set; }
        public string Date_of_Posting { get; set; }
        public Nullable<int> IJP_Ageing { get; set; }
        public string Last_Date_of_Application { get; set; }
        public string Type__Vertical___Lateral_ { get; set; }
        public string HRBP { get; set; }
        public string Hiring_Manager { get; set; }
        public string IJP_Release_Month { get; set; }
        public string Results_Announced_on { get; set; }
        public string Status { get; set; }
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_LOB { get; set; }
        public string Employee_Process_Name { get; set; }
        public string Designation { get; set; }
        public string Supervisor { get; set; }
        public string DOJ { get; set; }
        public string Date_of_Movement { get; set; }
        public string Month_of_Movement { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> fltdt { get; set; }
        public Nullable<long> fltuser { get; set; }
    }
}
