//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NDReport_IJPApplicationsReport
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public string LOB { get; set; }
        public int Total_no__of_positions { get; set; }
        public Nullable<int> Number_of_positions_closed { get; set; }
        public string IJP_Number { get; set; }
        public string IJP_for { get; set; }
        public string HRBP { get; set; }
        public string Date_of_Posting { get; set; }
        public string Last_Date_of_Application { get; set; }
        public string EMP_ID { get; set; }
        public string Name_of_the_Candidate { get; set; }
        public string Employee_LOB { get; set; }
        public string Process { get; set; }
        public string Position_Title { get; set; }
        public string Reports_to_Name { get; set; }
        public string DOJ { get; set; }
        public string P4P { get; set; }
        public string PDP_Rating { get; set; }
        public short Disciplinary_Action { get; set; }
        public int Total_Tenure_in_MetLife { get; set; }
        public int Attempts { get; set; }
        public string Status { get; set; }
        public string Hiring_Leader { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> fltdt { get; set; }
        public Nullable<long> fltuser { get; set; }
    }
}
