//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NDReport_SRFOfferJoiningReport
    {
        public long RID { get; set; }
        public long ReqID { get; set; }
        public string SRF_No_ { get; set; }
        public string Entity { get; set; }
        public string Process_ID { get; set; }
        public string Cost_Centre { get; set; }
        public string LOB { get; set; }
        public string Sub_LOB { get; set; }
        public string MM_FL { get; set; }
        public string Process_Name { get; set; }
        public string Hiring_Leader { get; set; }
        public string Reporting_Manager { get; set; }
        public string Functional_Leader { get; set; }
        public string Function__Enabling___Ops_ { get; set; }
        public string Level___Associate___Sr___Associate___Splst___BPS___QA__TL___AM___UM___Mgr___Sr_Mgr___SDL___Dir_ { get; set; }
        public string Work_Type__Generic___Specialized_ { get; set; }
        public string Hiring_Type__Migration___Ramp_up___Backfill___Predictive_Backfill_ { get; set; }
        public string Name_of_Candidate_Attrited { get; set; }
        public string Designation_of_candidate_attrited { get; set; }
        public string SRF_Date { get; set; }
        public string SRF_Month { get; set; }
        public Nullable<int> SRF_Age__Weeks_ { get; set; }
        public Nullable<int> Approved_TAT { get; set; }
        public string Requisition__Open___Closed___On_Hold___Cancel_ { get; set; }
        public string SRF_Owner { get; set; }
        public decimal Billable_FTE { get; set; }
        public decimal Buffer_HC { get; set; }
        public int HC { get; set; }
        public int Offered__1_0_ { get; set; }
        public int Joined__1_0_ { get; set; }
        public string M___F { get; set; }
        public string Candidate_Name { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Comp { get; set; }
        public string JD_Share_Date { get; set; }
        public string Channel { get; set; }
        public string Source_Details { get; set; }
        public string Resume_Received_Date__Supplier_Process_ { get; set; }
        public string HR_Screening_Completion_Date { get; set; }
        public string Business_Intimated_Date { get; set; }
        public string Business_Interaction_Closure_Date { get; set; }
        public string HRBP_Interview { get; set; }
        public string Stage { get; set; }
        public string Status { get; set; }
        public string Feedback { get; set; }
        public string Offer_Roll_out_Date { get; set; }
        public string Date_of_Joining { get; set; }
        public Nullable<int> Time_Taken_to_Identify_a_Resource { get; set; }
        public Nullable<int> Time_Taken_to_Onboard { get; set; }
        public string Names_of_Ops_Assesors_Hiring_Manager___Contact_Number { get; set; }
        public string C_Assesment_Single___Dual__ { get; set; }
        public string Client_Assessment { get; set; }
        public string Exception_Approval_Taken_on_Comp { get; set; }
        public string Compensation_approved_by { get; set; }
        public Nullable<int> Exceeded_TAT__0___Within_TAT_1_ { get; set; }
        public string RACF_ID { get; set; }
        public string Ops1_Feedback { get; set; }
        public string Ops2_Feedback { get; set; }
        public string Place_of_interview { get; set; }
        public string Last_Fixed_Compensation_of_Offered_Canddiate { get; set; }
        public string Compensation_offered_at_MetLife_Fixed { get; set; }
        public string Travel_Cost { get; set; }
        public decimal Guest_House_Cost { get; set; }
        public decimal Relocation_Cost { get; set; }
        public decimal Joining_Bonus { get; set; }
        public decimal Notice_Period_Payout { get; set; }
        public string Total_Fixed_Cost_of_Canddiate_without_PF_and_Gratuity { get; set; }
        public string Commission_Rate { get; set; }
        public decimal Expected_Billing_of_Consultant___Referral { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string DOB { get; set; }
        public string Higest_Education_Level { get; set; }
        public string Marital_Status { get; set; }
        public string PAN_ID { get; set; }
        public string Home_Address_1 { get; set; }
        public string Home_Address_2 { get; set; }
        public string Home_Address_3 { get; set; }
        public string Home_City { get; set; }
        public int Postal_Code { get; set; }
        public string Alt_Phone_ { get; set; }
        public string Mobile_phone_ { get; set; }
        public string Designation { get; set; }
        public string Supervisors_name { get; set; }
        public decimal Annual_Comp_Rate { get; set; }
        public string Permanent_Address { get; set; }
        public string Father_s_Name { get; set; }
        public string Bank_Account_Nos_ { get; set; }
        public string Spouse_Name { get; set; }
        public string Spouse_Dob { get; set; }
        public string Son_s_Name { get; set; }
        public string Son_s_Dob { get; set; }
        public string Daughter_s_Name { get; set; }
        public string Daughter_s_Dob { get; set; }
        public string Graduation__Stream_ { get; set; }
        public Nullable<System.DateTime> fltdt { get; set; }
        public Nullable<long> fltuser { get; set; }
    }
}
