//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ND_RecruiterPerformanceReport
    {
        public string Interviewer_name { get; set; }
        public int No_of_requisition_allocated { get; set; }
        public int No_of_openi_ngs_allocated { get; set; }
        public int Resume_tagged { get; set; }
        public int Screening_selected { get; set; }
        public int CET_selected { get; set; }
        public int Personal_Interview_selected { get; set; }
        public int Line_Interview_selected { get; set; }
        public int PSA_selected { get; set; }
        public int Client_selected { get; set; }
        public int Offered { get; set; }
        public int Joined { get; set; }
    }
}
