//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NDReportGMCDeletion
    {
        public long rid { get; set; }
        public string EmpID { get; set; }
        public string SAPID { get; set; }
        public string PrimaryInsuredName { get; set; }
        public string DateofBirth { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string RelationType { get; set; }
        public string DateofJoining { get; set; }
        public string RiskInceptionDate { get; set; }
        public string GradeDesignation { get; set; }
        public Nullable<System.DateTime> QDate { get; set; }
    }
}
