//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NDReportClosedRequirementStatus
    {
        public long rid { get; set; }
        public string Role { get; set; }
        public string JobCode { get; set; }
        public string BusinessUnit { get; set; }
        public string Department { get; set; }
        public string Function { get; set; }
        public string Designation { get; set; }
        public string HiringManager { get; set; }
        public string EmploymentType { get; set; }
        public string Location { get; set; }
        public string VCFinalApprovalDate { get; set; }
        public System.DateTime TargetDate { get; set; }
        public string RecruitmentStatus { get; set; }
        public string ApprovedBy { get; set; }
        public int Position { get; set; }
        public Nullable<long> Age { get; set; }
        public short SLA { get; set; }
        public string SLATAT { get; set; }
        public Nullable<System.DateTime> ClosedCancelledDate { get; set; }
        public int TotalResume { get; set; }
        public int HMShortlist { get; set; }
        public int Interview { get; set; }
        public int InterviewSelect { get; set; }
        public int OfferMade { get; set; }
        public int OfferAccepted { get; set; }
        public int Joined { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
