//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NDReportBudgetDetail
    {
        public long rid { get; set; }
        public string BudgetYear { get; set; }
        public string Company { get; set; }
        public string BusinessUnit { get; set; }
        public string Department { get; set; }
        public long Q1 { get; set; }
        public long Q2 { get; set; }
        public long Q3 { get; set; }
        public long Q4 { get; set; }
        public long Total { get; set; }
        public long Available { get; set; }
        public int Utilized { get; set; }
    }
}
