//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RecruitmentCycleTimeReport
    {
        public long ReqResID { get; set; }
        public long ResID { get; set; }
        public long ReqID { get; set; }
        public Nullable<long> GradeID { get; set; }
        public string RequisitionTitle { get; set; }
        public string JobCode { get; set; }
        public string BU { get; set; }
        public string Location { get; set; }
        public Nullable<long> AssignedAnchorID { get; set; }
        public System.DateTime ApplicantCreatedDate { get; set; }
        public string Requester { get; set; }
        public System.DateTime ReqCreatedDate { get; set; }
        public string ReqApproved { get; set; }
        public System.DateTime ReqTargetDate { get; set; }
        public string ReqStatus { get; set; }
        public int ReqAge { get; set; }
        public string CandidateName { get; set; }
        public string CandidateNo { get; set; }
        public string CandidateSource { get; set; }
        public string CandidateStage { get; set; }
        public string CandidateStatus { get; set; }
        public System.DateTime CandidateAddedDate { get; set; }
        public System.DateTime CVSentDate { get; set; }
        public Nullable<long> CVSentTAT { get; set; }
        public System.DateTime ShortlistDate { get; set; }
        public Nullable<long> ShortlistTAT { get; set; }
        public System.DateTime FirstInterviewDate { get; set; }
        public Nullable<long> FirstInterviewTAT { get; set; }
        public System.DateTime SecondInterviewDate { get; set; }
        public Nullable<long> SecondInterviewTAT { get; set; }
        public System.DateTime FinalInterviewDate { get; set; }
        public Nullable<long> FinalInterviewTAT { get; set; }
        public System.DateTime OfferPendingDate { get; set; }
        public System.DateTime OfferApprovedDate { get; set; }
        public Nullable<long> OfferApprovedTAT { get; set; }
        public System.DateTime OfferReleaseDate { get; set; }
        public Nullable<long> OfferReleaseTAT { get; set; }
        public System.DateTime OfferAcceptedDate { get; set; }
        public Nullable<long> OfferAcceptedTAT { get; set; }
        public System.DateTime JoinedDate { get; set; }
        public Nullable<long> JoinedTAT { get; set; }
        public System.DateTime DropDate { get; set; }
        public Nullable<long> DropTAT { get; set; }
        public string DropReason { get; set; }
    }
}
