//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ResumeDailyReport
    {
        public long RID { get; set; }
        public string Ticket_No { get; set; }
        public string CandidateName { get; set; }
        public string Gender { get; set; }
        public string Mobile_No { get; set; }
        public string Education { get; set; }
        public string DOB { get; set; }
        public string Email_ID { get; set; }
        public decimal Total_Experience { get; set; }
        public decimal Relevant_Experience { get; set; }
        public string Location { get; set; }
        public string Source { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Source_Ref { get; set; }
        public string Interview_Status { get; set; }
        public string CET_Status { get; set; }
        public string Screening_Status { get; set; }
        public string Interview_Panel_Member { get; set; }
    }
}
