//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_source_data
    {
        public long RID { get; set; }
        public string Centre_Name { get; set; }
        public string Office { get; set; }
        public string Hiring_Type { get; set; }
        public string Circle { get; set; }
        public string LOB { get; set; }
        public string Process { get; set; }
        public string Added_On { get; set; }
        public string Interview_Date { get; set; }
        public string Student_ID { get; set; }
        public string Ticket_Number { get; set; }
        public string Job_Code { get; set; }
        public string Grade { get; set; }
        public string Requisition_Type { get; set; }
        public string Candidate_Name { get; set; }
        public string Date_of_Birth { get; set; }
        public string Qualification { get; set; }
        public string Gender { get; set; }
        public string Candidate_Location { get; set; }
        public string Candidate_Contact_No { get; set; }
        public string Email_ID { get; set; }
        public string Interviewer { get; set; }
        public string Source { get; set; }
        public string Source_ID { get; set; }
        public string Stage { get; set; }
        public string Status { get; set; }
        public string Reject_Reason { get; set; }
        public decimal CET_Score { get; set; }
        public string PSA_Score { get; set; }
        public string Enrollment_Date { get; set; }
        public string Conditional_Code { get; set; }
        public long Course_Fee { get; set; }
        public string Scholarship_Discount_Amt_ { get; set; }
        public string Enrollment_Fee { get; set; }
        public string Pending_Fee_Amt_ { get; set; }
        public long C1st_Instalment { get; set; }
        public string Cash_Receipt_No_ { get; set; }
        public string Bank_Deposited_Amt { get; set; }
        public string Bank_Deposit_Date { get; set; }
        public string Deposit_Slip_No_ { get; set; }
        public string C2nd_Instalment { get; set; }
        public string Cash_Receipt_No__2 { get; set; }
        public string C2nd_Bank_Deposited_Amt { get; set; }
        public string C2nd_Bank_Deposit_Date { get; set; }
        public string C2nd_Deposit_Slip_No_ { get; set; }
        public long Refund_Amt { get; set; }
        public string Refund_Date { get; set; }
        public string Reason_for_Refund { get; set; }
        public string Non_recoverable_amount { get; set; }
        public string Reasons_for_non_Recovery { get; set; }
        public string Reject_Remarks { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
