//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Tallint_Data
    {
        public string UserName { get; set; }
        public string Jobcode { get; set; }
        public string Location { get; set; }
        public string Typ { get; set; }
    }
}
