//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VendorReferralReport
    {
        public long ReqResID { get; set; }
        public long ReqID { get; set; }
        public string VendorName { get; set; }
        public long ClientID { get; set; }
        public string Client { get; set; }
        public string BU { get; set; }
        public string Location { get; set; }
        public string RequisitionTitle { get; set; }
        public string JobCode { get; set; }
        public System.DateTime ReqCreatedDate { get; set; }
        public System.DateTime ApplicantCreatedDate { get; set; }
        public Nullable<long> AssignedAnchorID { get; set; }
        public Nullable<long> GradeID { get; set; }
        public string Anchor { get; set; }
        public string CandidateName { get; set; }
        public string CandidateStage { get; set; }
        public string CandidateStatus { get; set; }
        public string TicketNo { get; set; }
    }
}
